
site_name: FalconPM Documentation
site_url: https://mareekkk.github.io/FPM-docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: indigo
      accent: pink

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Changelog: changelog.md